from tkinter import *
import tkinter as tk
from tkinter import ttk
import tkinter
from tkinter import messagebox
from datetime import *
import random


from abc import ABC, abstractmethod


class CaliforniaPizza(ABC):
    @abstractmethod
    def __init__(self):
        pass
class item(CaliforniaPizza):
    def __init__(self,name, price):
        self.name = name
        self.price = price


supersupreme= item("Super Supreme",1500)
chickensupreme= item("chicken supreme",1000)
beefsupreme= item("beef supreme",1250)
chickentikka= item("chicken tikka",1100)
chickenfajita=item("chicken fajita",1300)
vegielover= item("vegie lover",900)
creamytikka= item("Creamy Tikka",1400)
deal1 = item("Deal 1" ,1939)
deal2 = item("Deal 2" ,2500)
deal3 = item("Deal 3" ,2600)
deal4 = item("Deal 4" ,2700)
deal5 = item("Deal 5" ,3000)
deal6 = item("Deal 6" ,3749)
kiddeal1 = item("Deal 1" ,2500)
kiddeal2 = item("Deal 2" ,2600)
chocolate= item("Chocolate Heaven cake",275)
softdrink500 = item("Softdrink 500ml",100)
softdrink15 = item("Softdrink 1.5L",150)
water500 = item("Softdrink 500ml",60)
water15 = item("Water 1.5L",100)
mexicansw = item("Mexican Sandwich",429)
chickenlas = item("Chicken Lasagna", 569)
cheesyfries = item("Cheesy Fries",369)
chickenpasta = item("Chicken Pasta",569)
gbread = item("Garlic Bread",289)
chbread = item("Cheesy Bread",269)
crispyf = item("Crispy Fries",149)
friesgm = item("Fries Garlic Mayo",200)
rcheese = item("Chees",219)
lcheese = item("Chees",319)
jcheese = item("Chees",359)
rmeat = item("Chees",179)
lmeat = item("Chees",255)
jmeat = item("Chees",285)

class reset:
    def Reset(self):
        Entry1.delete("0", END)
        Entry2.delete("0", END)
        Entry3.delete("0", END)
        Entry4.delete("0", END)
        Entry5.delete("0", END)
        Entry6.delete("0", END)
        Entry7.delete("0", END)
        Entry8.delete("0", END)
        Entry9.delete("0", END)
        Entry10.delete("0", END)
        Entry11.delete("0", END)
        Entry12.delete("0", END)
        Entry13.delete("0", END)
        Entry14.delete("0", END)
        Entry15.delete("0", END)
        Entry16.delete("0", END)
        Entry17.delete("0", END)
        Entry18.delete("0", END)
        Entry19.delete("0", END)
        Entry20.delete("0", END)
        Entry21.delete("0", END)
        Entry22.delete("0", END)
        Entry23.delete("0", END)
        Entry24.delete("0", END)
        Entry25.delete("0", END)
        Entry26.delete("0", END)
        Entry27.delete("0", END)
        Entry28.delete("0", END)
        Entry29.delete("0", END)
        Entry30.delete("0", END)
        Entry31.delete("0", END)
        Entry32.delete("0", END)
        Entry33.delete("0", END)
        Entry34.delete("0", END)
        Entry1.insert(0,"0")
        Entry2.insert(0, "0")
        Entry3.insert(0, "0")
        Entry4.insert(0, "0")
        Entry5.insert(0, "0")
        Entry6.insert(0, "0")
        Entry7.insert(0, "0")
        Entry8.insert(0, "0")
        Entry9.insert(0, "0")
        Entry10.insert(0, "0")
        Entry11.insert(0, "0")
        Entry12.insert(0, "0")
        Entry13.insert(0, "0")
        Entry14.insert(0, "0")
        Entry15.insert(0, "0")
        Entry16.insert(0, "0")
        Entry17.insert(0, "0")
        Entry18.insert(0, "0")
        Entry19.insert(0, "0")
        Entry20.insert(0, "0")
        Entry21.insert(0, "0")
        Entry22.insert(0, "0")
        Entry23.insert(0, "0")
        Entry24.insert(0, "0")
        Entry25.insert(0, "0")
        Entry26.insert(0, "0")
        Entry27.insert(0, "0")
        Entry28.insert(0, "0")
        Entry29.insert(0, "0")
        Entry30.insert(0, "0")
        Entry31.insert(0, "0")
        Entry32.insert(0, "0")
        Entry33.insert(0, "0")
        Entry34.insert(0, "0")

class total:

    def calculation(self):
        global Total
        ent1= int(Entry1.get())
        ent2 = int(Entry2.get())
        ent3 = int(Entry3.get())
        ent4 = int(Entry4.get())
        ent5 = int(Entry5.get())
        ent6 = int(Entry6.get())
        ent7 = int(Entry7.get())
        ent8 = int(Entry8.get())
        ent9 = int(Entry9.get())
        ent10 = int(Entry10.get())
        ent11 = int(Entry11.get())
        ent12 = int(Entry12.get())
        ent13 = int(Entry13.get())
        ent14 = int(Entry14.get())
        ent15 = int(Entry15.get())
        ent16 = int(Entry16.get())
        ent17 = int(Entry17.get())
        ent18= int(Entry18.get())
        ent19 =int(Entry19.get())
        ent20 =int(Entry20.get())
        ent21 = int(Entry21.get())
        ent22 = int(Entry22.get())
        ent23 = int(Entry23.get())
        ent24 = int(Entry24.get())
        ent25 = int(Entry25.get())
        ent26 = int(Entry26.get())
        ent27 = int(Entry27.get())
        ent28 = int(Entry28.get())
        ent29 = int(Entry29.get())
        ent30 = int(Entry30.get())
        ent31 = int(Entry31.get())
        ent32 = int(Entry32.get())
        ent33 = int(Entry33.get())
        ent34 = int(Entry34.get())
        Total = ((supersupreme.price * ent1)+(chickensupreme.price * ent2)+(beefsupreme.price * ent3)+(chickentikka.price * ent4)+(chickenfajita.price * ent5)+(vegielover.price * ent6)+
                 (creamytikka.price * ent7)+ (deal1.price * ent8)+(deal2.price * ent9)+(deal3.price * ent10)+(deal4.price * ent11)+(deal5.price * ent12)+(deal6.price * ent13)+(gbread.price * ent14)+
                 (chbread.price * ent15)+(crispyf.price * ent16)+(friesgm.price * ent17)+(softdrink500.price * ent18)+(softdrink15.price * ent19)+(water500.price * ent20)+
                 (water15.price * ent21)+(chocolate.price * ent22)+(rcheese.price * ent23)+(rmeat.price * ent24)+(lcheese.price * ent25)+(lmeat.price * ent26)+
                 (jcheese.price * ent27)+(jmeat.price * ent28)+(mexicansw.price * ent29)+(chickenlas.price * ent30)+(cheesyfries.price * ent31)+(chickenpasta.price * ent32)+
                 (kiddeal1.price * ent33)+(kiddeal2.price * ent34))
        print(Total)


class GUI:

    def maingui(self):
        global Entry1, Entry2, top
        top = Tk()
        top.geometry("597x450+509+200")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("California Pizza POS")
        top.configure(background="#ffffff")

        Frame1 = tk.Frame(top)
        Frame1.place(relx=-0.017, rely=0.0, relheight=0.260, relwidth=1.107)

        Frame1.configure(relief='groove')
        Frame1.configure(borderwidth="2")
        Frame1.configure(relief="groove")
        Frame1.configure(background="#ffffff")

        photo = PhotoImage(file = 'logo.png')
        framepic = Label(Frame1,image = photo)
        framepic.pack()

        Label1 = tk.Label(top)
        Label1.place(relx=0.309, rely=0.282, height=46, width=253)
        Label1.configure(background="#ffffff")
        Label1.configure(disabledforeground="#a3a3a3")
        Label1.configure(font=9)
        Label1.configure(foreground="#b90746")
        Label1.configure(text='''LOGIN/REGISTER''')

        Entry1 = tk.Entry(top)
        Entry1.place(relx=0.352, rely=0.422, height=34, relwidth=0.308)
        Entry1.configure(background="white")
        Entry1.configure(disabledforeground="#a3a3a3")
        Entry1.configure(font="TkFixedFont")
        Entry1.configure(foreground="#000000")
        Entry1.configure(insertbackground="black")

        Entry2 = tk.Entry(top)
        Entry2.place(relx=0.352, rely=0.533, height=34, relwidth=0.308)
        Entry2.configure(background="white")
        Entry2.configure(disabledforeground="#a3a3a3")
        Entry2.configure(font="TkFixedFont")
        Entry2.configure(foreground="#000000")
        Entry2.configure(insertbackground="black")

        Label2 = tk.Label(top)
        Label2.place(relx=0.201, rely=0.422, height=36, width=62)
        Label2.configure(background="#ffffff")
        Label2.configure(disabledforeground="#a3a3a3")
        Label2.configure(font=10)
        Label2.configure(foreground="#b90746")
        Label2.configure(text='''USER''')

        Label3 = tk.Label(top)
        Label3.place(relx=0.134, rely=0.533, height=36, width=122)
        Label3.configure(background="#ffffff")
        Label3.configure(disabledforeground="#a3a3a3")
        Label3.configure(font=10)
        Label3.configure(foreground="#b90746")
        Label3.configure(text='''PASSWORD''')

        Button1 = tk.Button(top,command = login)
        Button1.place(relx=0.335, rely=0.689, height=43, width=86)
        Button1.configure(activebackground="#ececec")
        Button1.configure(activeforeground="#000000")
        Button1.configure(background="#b90746")
        Button1.configure(disabledforeground="#a3a3a3")
        Button1.configure(foreground="#ffffff")
        Button1.configure(highlightbackground="#d9d9d9")
        Button1.configure(highlightcolor="black")
        Button1.configure(pady="0")
        Button1.configure(text='''LOGIN''')

        Button2 = tk.Button(top, command=register)
        Button2.place(relx=0.519, rely=0.689, height=43, width=106)
        Button2.configure(activebackground="#ececec")
        Button2.configure(activeforeground="#000000")
        Button2.configure(background="#b90746")
        Button2.configure(disabledforeground="#a3a3a3")
        Button2.configure(foreground="#ffffff")
        Button2.configure(highlightbackground="#d9d9d9")
        Button2.configure(highlightcolor="black")
        Button2.configure(pady="0")
        Button2.configure(text='''REGISTER''')
        top.mainloop()

    def secondwindow(self):
        global Entry1,Entry2,Entry3,Entry4,Entry5,Entry6,Entry7,Entry8,Entry9,Entry10,Entry11,Entry12,Entry13,Entry14,Entry15,Entry16,Entry17,Entry18,Entry19,Entry20,Entry21,Entry22,Entry23,Entry24,Entry25,Entry26,Entry27,Entry28,Entry29,Entry30,Entry31,Entry32,Entry33,Entry34
        top = Tk()
        top.geometry("1443x1345+0+0")
        top.minsize(148, 1)
        top.maxsize(1916, 1047)
        top.state('zoomed')
        top.resizable(1, 1)
        top.title("CALIFORNIA PIZZA POS")
        top.configure(background="#ffffff")

        Frame_1 = tk.Frame(top)
        Frame_1.place(relx=-0.007, rely=0.0, relheight=0.168, relwidth=1.002)

        Frame_1.configure(relief='groove')
        Frame_1.configure(borderwidth="2")
        Frame_1.configure(relief="groove")
        Frame_1.configure(background="#ffffff")

        photo = PhotoImage(file='logo.png')
        framepic = Label(Frame_1, image=photo)
        framepic.pack()

        Label1 = tk.Label(top)
        Label1.place(relx=0.022, rely=0.177, height=36, width=138)
        Label1.configure(background="#ffffff")
        Label1.configure(disabledforeground="#a3a3a3")
        Label1.configure(font=18)
        Label1.configure(
            font="-family {Copperplate Gothic Bold} -size 18 -weight bold -slant roman -underline 0 -overstrike 0")

        Label1.configure(foreground="#b90746")
        Label1.configure(text='''PIZZA''')

        Label2 = tk.Label(top)
        Label2.place(relx=0.0, rely=0.221, height=36, width=216)
        Label2.configure(activebackground="#f9f9f9")
        Label2.configure(activeforeground="black")
        Label2.configure(background="#ffffff")
        Label2.configure(disabledforeground="#a3a3a3")
        Label2.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label2.configure(foreground="#008000")
        Label2.configure(highlightbackground="#d9d9d9")
        Label2.configure(highlightcolor="black")
        Label2.configure(text='''SUPER SUPREME''')

        Label3 = tk.Label(top)
        Label3.place(relx=0.007, rely=0.265, height=36, width=217)
        Label3.configure(activebackground="#f9f9f9")
        Label3.configure(activeforeground="black")
        Label3.configure(background="#ffffff")
        Label3.configure(disabledforeground="#a3a3a3")
        Label3.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label3.configure(foreground="#008000")
        Label3.configure(highlightbackground="#d9d9d9")
        Label3.configure(highlightcolor="black")
        Label3.configure(text='''CHICKEN SUPREME''')

        Label4 = tk.Label(top)
        Label4.place(relx=-0.007, rely=0.309, height=38, width=218)
        Label4.configure(activebackground="#f9f9f9")
        Label4.configure(activeforeground="black")
        Label4.configure(background="#ffffff")
        Label4.configure(disabledforeground="#a3a3a3")
        Label4.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label4.configure(foreground="#008000")
        Label4.configure(highlightbackground="#d9d9d9")
        Label4.configure(highlightcolor="black")
        Label4.configure(text='''BEEF SUPREME''')

        Label5 = tk.Label(top)
        Label5.place(relx=-0.007, rely=0.354, height=38, width=218)
        Label5.configure(activebackground="#f9f9f9")
        Label5.configure(activeforeground="black")
        Label5.configure(background="#ffffff")
        Label5.configure(disabledforeground="#a3a3a3")
        Label5.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label5.configure(foreground="#008000")
        Label5.configure(highlightbackground="#d9d9d9")
        Label5.configure(highlightcolor="black")
        Label5.configure(text='''CHICKEN TIKKA''')

        Label6 = tk.Label(top)
        Label6.place(relx=0.0, rely=0.398, height=38, width=208)
        Label6.configure(activebackground="#f9f9f9")
        Label6.configure(activeforeground="black")
        Label6.configure(background="#ffffff")
        Label6.configure(disabledforeground="#a3a3a3")
        Label6.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label6.configure(foreground="#008000")
        Label6.configure(highlightbackground="#d9d9d9")
        Label6.configure(highlightcolor="black")
        Label6.configure(text='''CHICKEN FAJITA''')

        Label7 = tk.Label(top)
        Label7.place(relx=-0.007, rely=0.442, height=38, width=198)
        Label7.configure(activebackground="#f9f9f9")
        Label7.configure(activeforeground="black")
        Label7.configure(background="#ffffff")
        Label7.configure(disabledforeground="#a3a3a3")
        Label7.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label7.configure(foreground="#008000")
        Label7.configure(highlightbackground="#d9d9d9")
        Label7.configure(highlightcolor="black")
        Label7.configure(text='''VEGIE LOVER''')

        Label7 = tk.Label(top)
        Label7.place(relx=-0.007, rely=0.486, height=38, width=208)
        Label7.configure(activebackground="#f9f9f9")
        Label7.configure(activeforeground="black")
        Label7.configure(background="#ffffff")
        Label7.configure(disabledforeground="#a3a3a3")
        Label7.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label7.configure(foreground="#008000")
        Label7.configure(highlightbackground="#d9d9d9")
        Label7.configure(highlightcolor="black")
        Label7.configure(text='''CREAMY TIKKA''')

        Entry1 = tk.Entry(top)
        Entry1.place(relx=0.173, rely=0.232, height=24, relwidth=0.051)
        Entry1.configure(background="white")
        Entry1.configure(disabledforeground="#a3a3a3")
        Entry1.configure(font="TkFixedFont")
        Entry1.configure(foreground="#000000")
        Entry1.configure(insertbackground="black")
        Entry1.insert(0,"0")

        Entry2 = tk.Entry(top)
        Entry2.place(relx=0.175, rely=0.276, height=24, relwidth=0.051)
        Entry2.configure(background="white")
        Entry2.configure(disabledforeground="#a3a3a3")
        Entry2.configure(font="TkFixedFont")
        Entry2.configure(foreground="#000000")
        Entry2.configure(highlightbackground="#d9d9d9")
        Entry2.configure(highlightcolor="black")
        Entry2.configure(insertbackground="black")
        Entry2.configure(selectbackground="#c4c4c4")
        Entry2.configure(selectforeground="black")
        Entry2.insert(0, "0")

        Entry3 = tk.Entry(top)
        Entry3.place(relx=0.175, rely=0.32, height=24, relwidth=0.051)
        Entry3.configure(background="white")
        Entry3.configure(disabledforeground="#a3a3a3")
        Entry3.configure(font="TkFixedFont")
        Entry3.configure(foreground="#000000")
        Entry3.configure(highlightbackground="#d9d9d9")
        Entry3.configure(highlightcolor="black")
        Entry3.configure(insertbackground="black")
        Entry3.configure(selectbackground="#c4c4c4")
        Entry3.configure(selectforeground="black")
        Entry3.insert(0, "0")

        Entry4 = tk.Entry(top)
        Entry4.place(relx=0.175, rely=0.365, height=24, relwidth=0.051)
        Entry4.configure(background="white")
        Entry4.configure(disabledforeground="#a3a3a3")
        Entry4.configure(font="TkFixedFont")
        Entry4.configure(foreground="#000000")
        Entry4.configure(highlightbackground="#d9d9d9")
        Entry4.configure(highlightcolor="black")
        Entry4.configure(insertbackground="black")
        Entry4.configure(selectbackground="#c4c4c4")
        Entry4.configure(selectforeground="black")
        Entry4.insert(0, "0")

        Entry5 = tk.Entry(top)
        Entry5.place(relx=0.175, rely=0.409, height=24, relwidth=0.051)
        Entry5.configure(background="white")
        Entry5.configure(disabledforeground="#a3a3a3")
        Entry5.configure(font="TkFixedFont")
        Entry5.configure(foreground="#000000")
        Entry5.configure(highlightbackground="#d9d9d9")
        Entry5.configure(highlightcolor="black")
        Entry5.configure(insertbackground="black")
        Entry5.configure(selectbackground="#c4c4c4")
        Entry5.configure(selectforeground="black")
        Entry5.insert(0, "0")

        Entry6 = tk.Entry(top)
        Entry6.place(relx=0.175, rely=0.453, height=24, relwidth=0.051)
        Entry6.configure(background="white")
        Entry6.configure(disabledforeground="#a3a3a3")
        Entry6.configure(font="TkFixedFont")
        Entry6.configure(foreground="#000000")
        Entry6.configure(highlightbackground="#d9d9d9")
        Entry6.configure(highlightcolor="black")
        Entry6.configure(insertbackground="black")
        Entry6.configure(selectbackground="#c4c4c4")
        Entry6.configure(selectforeground="black")
        Entry6.insert(0, "0")

        Entry7 = tk.Entry(top)
        Entry7.place(relx=0.175, rely=0.497, height=24, relwidth=0.051)
        Entry7.configure(background="white")
        Entry7.configure(disabledforeground="#a3a3a3")
        Entry7.configure(font="TkFixedFont")
        Entry7.configure(foreground="#000000")
        Entry7.configure(highlightbackground="#d9d9d9")
        Entry7.configure(highlightcolor="black")
        Entry7.configure(insertbackground="black")
        Entry7.configure(selectbackground="#c4c4c4")
        Entry7.configure(selectforeground="black")
        Entry7.insert(0, "0")

        Label8 = tk.Label(top)
        Label8.place(relx=0.021, rely=0.552, height=36, width=149)
        Label8.configure(activebackground="#f9f9f9")
        Label8.configure(activeforeground="black")
        Label8.configure(background="#ffffff")
        Label8.configure(cursor="fleur")
        Label8.configure(disabledforeground="#a3a3a3")
        Label8.configure(
            font="-family {Copperplate Gothic Bold} -size 18 -weight bold -slant roman -underline 0 -overstrike 0")
        Label8.configure(foreground="#b90746")
        Label8.configure(highlightbackground="#d9d9d9")
        Label8.configure(highlightcolor="black")
        Label8.configure(text='''DEALS''')

        Label9 = tk.Label(top)
        Label9.place(relx=0.007, rely=0.597, height=46, width=129)
        Label9.configure(activebackground="#f9f9f9")
        Label9.configure(activeforeground="black")
        Label9.configure(background="#ffffff")
        Label9.configure(disabledforeground="#a3a3a3")
        Label9.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label9.configure(foreground="#008000")
        Label9.configure(highlightbackground="#d9d9d9")
        Label9.configure(highlightcolor="black")
        Label9.configure(text='''DEAL 1''')

        Label10 = tk.Label(top)
        Label10.place(relx=0.0, rely=0.652, height=37, width=153)
        Label10.configure(activebackground="#f9f9f9")
        Label10.configure(activeforeground="black")
        Label10.configure(background="#ffffff")
        Label10.configure(disabledforeground="#a3a3a3")
        Label10.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label10.configure(foreground="#008000")
        Label10.configure(highlightbackground="#d9d9d9")
        Label10.configure(highlightcolor="black")
        Label10.configure(text='''DEAL 2''')

        Label11 = tk.Label(top)
        Label11.place(relx=0.007, rely=0.696, height=46, width=130)
        Label11.configure(activebackground="#f9f9f9")
        Label11.configure(activeforeground="black")
        Label11.configure(background="#ffffff")
        Label11.configure(disabledforeground="#a3a3a3")
        Label11.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label11.configure(foreground="#008000")
        Label11.configure(highlightbackground="#d9d9d9")
        Label11.configure(highlightcolor="black")
        Label11.configure(text='''DEAL 3''')

        Label12 = tk.Label(top)
        Label12.place(relx=0.007, rely=0.807, height=37, width=131)
        Label12.configure(activebackground="#f9f9f9")
        Label12.configure(activeforeground="black")
        Label12.configure(background="#ffffff")
        Label12.configure(disabledforeground="#a3a3a3")
        Label12.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label12.configure(foreground="#008000")
        Label12.configure(highlightbackground="#d9d9d9")
        Label12.configure(highlightcolor="black")
        Label12.configure(text='''DEAL 5''')

        Label13 = tk.Label(top)
        Label13.place(relx=0.007, rely=0.751, height=37, width=130)
        Label13.configure(activebackground="#f9f9f9")
        Label13.configure(activeforeground="black")
        Label13.configure(background="#ffffff")
        Label13.configure(disabledforeground="#a3a3a3")
        Label13.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label13.configure(foreground="#008000")
        Label13.configure(highlightbackground="#d9d9d9")
        Label13.configure(highlightcolor="black")
        Label13.configure(text='''DEAL 4''')

        Label14 = tk.Label(top)
        Label14.place(relx=0.014, rely=0.862, height=37, width=103)
        Label14.configure(activebackground="#f9f9f9")
        Label14.configure(activeforeground="black")
        Label14.configure(background="#ffffff")
        Label14.configure(cursor="fleur")
        Label14.configure(disabledforeground="#a3a3a3")
        Label14.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label14.configure(foreground="#008000")
        Label14.configure(highlightbackground="#d9d9d9")
        Label14.configure(highlightcolor="black")
        Label14.configure(text='''DEAL 6''')

        Entry8 = tk.Entry(top)
        Entry8.place(relx=0.173, rely=0.597, height=24, relwidth=0.051)
        Entry8.configure(background="white")
        Entry8.configure(disabledforeground="#a3a3a3")
        Entry8.configure(font="TkFixedFont")
        Entry8.configure(foreground="#000000")
        Entry8.configure(highlightbackground="#d9d9d9")
        Entry8.configure(highlightcolor="black")
        Entry8.configure(insertbackground="black")
        Entry8.configure(selectbackground="#c4c4c4")
        Entry8.configure(selectforeground="black")
        Entry8.insert(0, "0")

        Entry9 = tk.Entry(top)
        Entry9.place(relx=0.173, rely=0.652, height=24, relwidth=0.051)
        Entry9.configure(background="white")
        Entry9.configure(disabledforeground="#a3a3a3")
        Entry9.configure(font="TkFixedFont")
        Entry9.configure(foreground="#000000")
        Entry9.configure(highlightbackground="#d9d9d9")
        Entry9.configure(highlightcolor="black")
        Entry9.configure(insertbackground="black")
        Entry9.configure(selectbackground="#c4c4c4")
        Entry9.configure(selectforeground="black")
        Entry9.insert(0, "0")

        Entry10 = tk.Entry(top)
        Entry10.place(relx=0.173, rely=0.707, height=24, relwidth=0.051)
        Entry10.configure(background="white")
        Entry10.configure(disabledforeground="#a3a3a3")
        Entry10.configure(font="TkFixedFont")
        Entry10.configure(foreground="#000000")
        Entry10.configure(highlightbackground="#d9d9d9")
        Entry10.configure(highlightcolor="black")
        Entry10.configure(insertbackground="black")
        Entry10.configure(selectbackground="#c4c4c4")
        Entry10.configure(selectforeground="black")
        Entry10.insert(0, "0")

        Entry11 = tk.Entry(top)
        Entry11.place(relx=0.173, rely=0.762, height=24, relwidth=0.051)
        Entry11.configure(background="white")
        Entry11.configure(disabledforeground="#a3a3a3")
        Entry11.configure(font="TkFixedFont")
        Entry11.configure(foreground="#000000")
        Entry11.configure(highlightbackground="#d9d9d9")
        Entry11.configure(highlightcolor="black")
        Entry11.configure(insertbackground="black")
        Entry11.configure(selectbackground="#c4c4c4")
        Entry11.configure(selectforeground="black")
        Entry11.insert(0, "0")

        Entry12 = tk.Entry(top)
        Entry12.place(relx=0.173, rely=0.818, height=24, relwidth=0.051)
        Entry12.configure(background="white")
        Entry12.configure(disabledforeground="#a3a3a3")
        Entry12.configure(font="TkFixedFont")
        Entry12.configure(foreground="#000000")
        Entry12.configure(highlightbackground="#d9d9d9")
        Entry12.configure(highlightcolor="black")
        Entry12.configure(insertbackground="black")
        Entry12.configure(selectbackground="#c4c4c4")
        Entry12.configure(selectforeground="black")
        Entry12.insert(0, "0")

        Entry13 = tk.Entry(top)
        Entry13.place(relx=0.173, rely=0.862, height=24, relwidth=0.051)
        Entry13.configure(background="white")
        Entry13.configure(disabledforeground="#a3a3a3")
        Entry13.configure(font="TkFixedFont")
        Entry13.configure(foreground="#000000")
        Entry13.configure(highlightbackground="#d9d9d9")
        Entry13.configure(highlightcolor="black")
        Entry13.configure(insertbackground="black")
        Entry13.configure(selectbackground="#c4c4c4")
        Entry13.configure(selectforeground="black")
        Entry13.insert(0, "0")

        Label15 = tk.Label(top)
        Label15.place(relx=0.326, rely=0.177, height=36, width=213)
        Label15.configure(activebackground="#f9f9f9")
        Label15.configure(activeforeground="black")
        Label15.configure(background="#ffffff")
        Label15.configure(disabledforeground="#a3a3a3")
        Label15.configure(
            font="-family {Copperplate Gothic Bold} -size 18 -weight bold -slant roman -underline 0 -overstrike 0")
        Label15.configure(foreground="#b90746")
        Label15.configure(highlightbackground="#d9d9d9")
        Label15.configure(highlightcolor="black")
        Label15.configure(text='''STARTERS''')

        Label16 = tk.Label(top)
        Label16.place(relx=0.333, rely=0.232, height=36, width=180)
        Label16.configure(activebackground="#f9f9f9")
        Label16.configure(activeforeground="black")
        Label16.configure(background="#ffffff")
        Label16.configure(disabledforeground="#a3a3a3")
        Label16.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label16.configure(foreground="#008000")
        Label16.configure(highlightbackground="#d9d9d9")
        Label16.configure(highlightcolor="black")
        Label16.configure(text='''GARLIC BREAD''')

        Label17 = tk.Label(top)
        Label17.place(relx=0.319, rely=0.287, height=36, width=230)
        Label17.configure(activebackground="#f9f9f9")
        Label17.configure(activeforeground="black")
        Label17.configure(background="#ffffff")
        Label17.configure(disabledforeground="#a3a3a3")
        Label17.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label17.configure(foreground="#008000")
        Label17.configure(highlightbackground="#d9d9d9")
        Label17.configure(highlightcolor="black")
        Label17.configure(text='''CHEESY BREAD''')

        Label18 = tk.Label(top)
        Label18.place(relx=0.326, rely=0.343, height=38, width=191)
        Label18.configure(activebackground="#f9f9f9")
        Label18.configure(activeforeground="black")
        Label18.configure(background="#ffffff")
        Label18.configure(disabledforeground="#a3a3a3")
        Label18.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label18.configure(foreground="#008000")
        Label18.configure(highlightbackground="#d9d9d9")
        Label18.configure(highlightcolor="black")
        Label18.configure(text='''CRISPY FRIES''')

        Label19 = tk.Label(top)
        Label19.place(relx=0.325, rely=0.398, height=36, width=265)
        Label19.configure(activebackground="#f9f9f9")
        Label19.configure(activeforeground="black")
        Label19.configure(background="#ffffff")
        Label19.configure(disabledforeground="#a3a3a3")
        Label19.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label19.configure(foreground="#008000")
        Label19.configure(highlightbackground="#d9d9d9")
        Label19.configure(highlightcolor="black")
        Label19.configure(text='''FRIES GARLIC MAYO''')

        Entry14 = tk.Entry(top)
        Entry14.place(relx=0.541, rely=0.232, height=24, relwidth=0.051)
        Entry14.configure(background="white")
        Entry14.configure(disabledforeground="#a3a3a3")
        Entry14.configure(font="TkFixedFont")
        Entry14.configure(foreground="#000000")
        Entry14.configure(highlightbackground="#d9d9d9")
        Entry14.configure(highlightcolor="black")
        Entry14.configure(insertbackground="black")
        Entry14.configure(selectbackground="#c4c4c4")
        Entry14.configure(selectforeground="black")
        Entry14.insert(0, "0")

        Entry15 = tk.Entry(top)
        Entry15.place(relx=0.541, rely=0.287, height=24, relwidth=0.051)
        Entry15.configure(background="white")
        Entry15.configure(disabledforeground="#a3a3a3")
        Entry15.configure(font="TkFixedFont")
        Entry15.configure(foreground="#000000")
        Entry15.configure(highlightbackground="#d9d9d9")
        Entry15.configure(highlightcolor="black")
        Entry15.configure(insertbackground="black")
        Entry15.configure(selectbackground="#c4c4c4")
        Entry15.configure(selectforeground="black")
        Entry15.insert(0, "0")

        Entry16 = tk.Entry(top)
        Entry16.place(relx=0.541, rely=0.343, height=24, relwidth=0.051)
        Entry16.configure(background="white")
        Entry16.configure(disabledforeground="#a3a3a3")
        Entry16.configure(font="TkFixedFont")
        Entry16.configure(foreground="#000000")
        Entry16.configure(highlightbackground="#d9d9d9")
        Entry16.configure(highlightcolor="black")
        Entry16.configure(insertbackground="black")
        Entry16.configure(selectbackground="#c4c4c4")
        Entry16.configure(selectforeground="black")
        Entry16.insert(0, "0")

        Entry17 = tk.Entry(top)
        Entry17.place(relx=0.541, rely=0.398, height=24, relwidth=0.051)
        Entry17.configure(background="white")
        Entry17.configure(disabledforeground="#a3a3a3")
        Entry17.configure(font="TkFixedFont")
        Entry17.configure(foreground="#000000")
        Entry17.configure(highlightbackground="#d9d9d9")
        Entry17.configure(highlightcolor="black")
        Entry17.configure(insertbackground="black")
        Entry17.configure(selectbackground="#c4c4c4")
        Entry17.configure(selectforeground="black")
        Entry17.insert(0, "0")

        Label20 = tk.Label(top)
        Label20.place(relx=0.728, rely=0.298, height=38, width=167)
        Label20.configure(activebackground="#f9f9f9")
        Label20.configure(activeforeground="black")
        Label20.configure(background="#ffffff")
        Label20.configure(disabledforeground="#a3a3a3")
        Label20.configure(
            font="-family {Copperplate Gothic Bold} -size 18 -weight bold -slant roman -underline 0 -overstrike 0")
        Label20.configure(foreground="#b90746")
        Label20.configure(highlightbackground="#d9d9d9")
        Label20.configure(highlightcolor="black")
        Label20.configure(text='''DRINKS''')

        Label21 = tk.Label(top)
        Label21.place(relx=0.631, rely=0.354, height=37, width=184)
        Label21.configure(activebackground="#f9f9f9")
        Label21.configure(activeforeground="black")
        Label21.configure(background="#ffffff")
        Label21.configure(disabledforeground="#a3a3a3")
        Label21.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label21.configure(foreground="#008000")
        Label21.configure(highlightbackground="#d9d9d9")
        Label21.configure(highlightcolor="black")
        Label21.configure(text='''SOFTDRINK''')

        Label22 = tk.Label(top)
        Label22.place(relx=0.811, rely=0.354, height=37, width=181)
        Label22.configure(activebackground="#f9f9f9")
        Label22.configure(activeforeground="black")
        Label22.configure(background="#ffffff")
        Label22.configure(cursor="fleur")
        Label22.configure(disabledforeground="#a3a3a3")
        Label22.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label22.configure(foreground="#008000")
        Label22.configure(highlightbackground="#d9d9d9")
        Label22.configure(highlightcolor="black")
        Label22.configure(text='''WATER''')

        Label23 = tk.Label(top)
        Label23.place(relx=0.644, rely=0.409, height=37, width=100)
        Label23.configure(activebackground="#f9f9f9")
        Label23.configure(activeforeground="black")
        Label23.configure(background="#ffffff")
        Label23.configure(disabledforeground="#a3a3a3")
        Label23.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label23.configure(foreground="#c10000")
        Label23.configure(highlightbackground="#d9d9d9")
        Label23.configure(highlightcolor="black")
        Label23.configure(text='''500 ml''')

        Label24 = tk.Label(top)
        Label24.place(relx=0.644, rely=0.464, height=36, width=98)
        Label24.configure(activebackground="#f9f9f9")
        Label24.configure(activeforeground="black")
        Label24.configure(background="#ffffff")
        Label24.configure(disabledforeground="#a3a3a3")
        Label24.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label24.configure(foreground="#c10000")
        Label24.configure(highlightbackground="#d9d9d9")
        Label24.configure(highlightcolor="black")
        Label24.configure(text='''1.5 l''')

        Entry18 = tk.Entry(top)
        Entry18.place(relx=0.721, rely=0.409, height=24, relwidth=0.044)
        Entry18.configure(background="white")
        Entry18.configure(cursor="fleur")
        Entry18.configure(disabledforeground="#a3a3a3")
        Entry18.configure(font="TkFixedFont")
        Entry18.configure(foreground="#000000")
        Entry18.configure(highlightbackground="#d9d9d9")
        Entry18.configure(highlightcolor="black")
        Entry18.configure(insertbackground="black")
        Entry18.configure(selectbackground="#c4c4c4")
        Entry18.configure(selectforeground="black")
        Entry18.insert(0, "0")

        Entry19 = tk.Entry(top)
        Entry19.place(relx=0.721, rely=0.475, height=24, relwidth=0.044)
        Entry19.configure(background="white")
        Entry19.configure(disabledforeground="#a3a3a3")
        Entry19.configure(font="TkFixedFont")
        Entry19.configure(foreground="#000000")
        Entry19.configure(highlightbackground="#d9d9d9")
        Entry19.configure(highlightcolor="black")
        Entry19.configure(insertbackground="black")
        Entry19.configure(selectbackground="#c4c4c4")
        Entry19.configure(selectforeground="black")
        Entry19.insert(0, "0")

        Label24 = tk.Label(top)
        Label24.place(relx=0.797, rely=0.398, height=36, width=98)
        Label24.configure(activebackground="#f9f9f9")
        Label24.configure(activeforeground="black")
        Label24.configure(background="#ffffff")
        Label24.configure(disabledforeground="#a3a3a3")
        Label24.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label24.configure(foreground="#c10000")
        Label24.configure(highlightbackground="#d9d9d9")
        Label24.configure(highlightcolor="black")
        Label24.configure(text='''500 ml''')

        Label25 = tk.Label(top)
        Label25.place(relx=0.797, rely=0.453, height=37, width=100)
        Label25.configure(activebackground="#f9f9f9")
        Label25.configure(activeforeground="black")
        Label25.configure(background="#ffffff")
        Label25.configure(disabledforeground="#a3a3a3")
        Label25.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label25.configure(foreground="#c10000")
        Label25.configure(highlightbackground="#d9d9d9")
        Label25.configure(highlightcolor="black")
        Label25.configure(text='''1.5 l''')

        Entry20 = tk.Entry(top)
        Entry20.place(relx=0.887, rely=0.409, height=24, relwidth=0.044)
        Entry20.configure(background="white")
        Entry20.configure(disabledforeground="#a3a3a3")
        Entry20.configure(font="TkFixedFont")
        Entry20.configure(foreground="#000000")
        Entry20.configure(highlightbackground="#d9d9d9")
        Entry20.configure(highlightcolor="black")
        Entry20.configure(insertbackground="black")
        Entry20.configure(selectbackground="#c4c4c4")
        Entry20.configure(selectforeground="black")
        Entry20.insert(0, "0")

        Entry21 = tk.Entry(top)
        Entry21.place(relx=0.887, rely=0.464, height=24, relwidth=0.044)
        Entry21.configure(background="white")
        Entry21.configure(disabledforeground="#a3a3a3")
        Entry21.configure(font="TkFixedFont")
        Entry21.configure(foreground="#000000")
        Entry21.configure(highlightbackground="#d9d9d9")
        Entry21.configure(highlightcolor="black")
        Entry21.configure(insertbackground="black")
        Entry21.configure(selectbackground="#c4c4c4")
        Entry21.configure(selectforeground="black")
        Entry21.insert(0, "0")

        Label26 = tk.Label(top)
        Label26.place(relx=0.714, rely=0.177, height=38, width=178)
        Label26.configure(activebackground="#f9f9f9")
        Label26.configure(activeforeground="black")
        Label26.configure(background="#ffffff")
        Label26.configure(disabledforeground="#a3a3a3")
        Label26.configure(
            font="-family {Copperplate Gothic Bold} -size 18 -weight bold -slant roman -underline 0 -overstrike 0")
        Label26.configure(foreground="#b90746")
        Label26.configure(highlightbackground="#d9d9d9")
        Label26.configure(highlightcolor="black")
        Label26.configure(text='''DESSERT''')

        Label27 = tk.Label(top)
        Label27.place(relx=0.658, rely=0.232, height=36, width=315)
        Label27.configure(activebackground="#f9f9f9")
        Label27.configure(activeforeground="black")
        Label27.configure(background="#ffffff")
        Label27.configure(disabledforeground="#a3a3a3")
        Label27.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label27.configure(foreground="#008000")
        Label27.configure(highlightbackground="#d9d9d9")
        Label27.configure(highlightcolor="black")
        Label27.configure(text='''CHOCOLATE HEAVEN CAKE''')

        Entry22 = tk.Entry(top)
        Entry22.place(relx=0.887, rely=0.232, height=34, relwidth=0.051)
        Entry22.configure(background="white")
        Entry22.configure(disabledforeground="#a3a3a3")
        Entry22.configure(font="TkFixedFont")
        Entry22.configure(foreground="#000000")
        Entry22.configure(highlightbackground="#d9d9d9")
        Entry22.configure(highlightcolor="black")
        Entry22.configure(insertbackground="black")
        Entry22.configure(selectbackground="#c4c4c4")
        Entry22.configure(selectforeground="black")
        Entry22.insert(0, "0")

        Label28 = tk.Label(top)
        Label28.place(relx=0.319, rely=0.541, height=38, width=338)
        Label28.configure(activebackground="#f9f9f9")
        Label28.configure(activeforeground="black")
        Label28.configure(background="#ffffff")
        Label28.configure(cursor="fleur")
        Label28.configure(disabledforeground="#a3a3a3")
        Label28.configure(
            font="-family {Copperplate Gothic Bold} -size 18 -weight bold -slant roman -underline 0 -overstrike 0")
        Label28.configure(foreground="#b90746")
        Label28.configure(highlightbackground="#d9d9d9")
        Label28.configure(highlightcolor="black")
        Label28.configure(text='''EXTRA TOPPINGS''')

        Label29 = tk.Label(top)
        Label29.place(relx=0.27, rely=0.597, height=37, width=134)
        Label29.configure(activebackground="#f9f9f9")
        Label29.configure(activeforeground="black")
        Label29.configure(background="#ffffff")
        Label29.configure(disabledforeground="#a3a3a3")
        Label29.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label29.configure(foreground="#008000")
        Label29.configure(highlightbackground="#d9d9d9")
        Label29.configure(highlightcolor="black")
        Label29.configure(text='''REGULAR''')

        Label30 = tk.Label(top)
        Label30.place(relx=0.402, rely=0.597, height=37, width=114)
        Label30.configure(activebackground="#f9f9f9")
        Label30.configure(activeforeground="black")
        Label30.configure(background="#ffffff")
        Label30.configure(disabledforeground="#a3a3a3")
        Label30.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label30.configure(foreground="#008000")
        Label30.configure(highlightbackground="#d9d9d9")
        Label30.configure(highlightcolor="black")
        Label30.configure(text='''LARGE''')

        Label31 = tk.Label(top)
        Label31.place(relx=0.52, rely=0.597, height=37, width=135)
        Label31.configure(activebackground="#f9f9f9")
        Label31.configure(activeforeground="black")
        Label31.configure(background="#ffffff")
        Label31.configure(disabledforeground="#a3a3a3")
        Label31.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label31.configure(foreground="#008000")
        Label31.configure(highlightbackground="#d9d9d9")
        Label31.configure(highlightcolor="black")
        Label31.configure(text='''JUMBO''')

        Label32 = tk.Label(top)
        Label32.place(relx=0.284, rely=0.652, height=37, width=99)
        Label32.configure(activebackground="#f9f9f9")
        Label32.configure(activeforeground="black")
        Label32.configure(background="#ffffff")
        Label32.configure(disabledforeground="#a3a3a3")
        Label32.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label32.configure(foreground="#c10000")
        Label32.configure(highlightbackground="#d9d9d9")
        Label32.configure(highlightcolor="black")
        Label32.configure(text='''CHEESE''')

        Label33 = tk.Label(top)
        Label33.place(relx=0.409, rely=0.652, height=37, width=100)
        Label33.configure(activebackground="#f9f9f9")
        Label33.configure(activeforeground="black")
        Label33.configure(background="#ffffff")
        Label33.configure(disabledforeground="#a3a3a3")
        Label33.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label33.configure(foreground="#c10000")
        Label33.configure(highlightbackground="#d9d9d9")
        Label33.configure(highlightcolor="black")
        Label33.configure(text='''CHEESE''')

        Label34 = tk.Label(top)
        Label34.place(relx=0.527, rely=0.652, height=37, width=100)
        Label34.configure(activebackground="#f9f9f9")
        Label34.configure(activeforeground="black")
        Label34.configure(background="#ffffff")
        Label34.configure(disabledforeground="#a3a3a3")
        Label34.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label34.configure(foreground="#c10000")
        Label34.configure(highlightbackground="#d9d9d9")
        Label34.configure(highlightcolor="black")
        Label34.configure(text='''CHEESE''')

        Label35 = tk.Label(top)
        Label35.place(relx=0.284, rely=0.707, height=37, width=99)
        Label35.configure(activebackground="#f9f9f9")
        Label35.configure(activeforeground="black")
        Label35.configure(background="#ffffff")
        Label35.configure(disabledforeground="#a3a3a3")
        Label35.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label35.configure(foreground="#c10000")
        Label35.configure(highlightbackground="#d9d9d9")
        Label35.configure(highlightcolor="black")
        Label35.configure(text='''MEAT''')

        Label36 = tk.Label(top)
        Label36.place(relx=0.409, rely=0.707, height=37, width=100)
        Label36.configure(activebackground="#f9f9f9")
        Label36.configure(activeforeground="black")
        Label36.configure(background="#ffffff")
        Label36.configure(disabledforeground="#a3a3a3")
        Label36.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label36.configure(foreground="#c10000")
        Label36.configure(highlightbackground="#d9d9d9")
        Label36.configure(highlightcolor="black")
        Label36.configure(text='''MEAT''')

        Label37 = tk.Label(top)
        Label37.place(relx=0.52, rely=0.707, height=37, width=100)
        Label37.configure(activebackground="#f9f9f9")
        Label37.configure(activeforeground="black")
        Label37.configure(background="#ffffff")
        Label37.configure(disabledforeground="#a3a3a3")
        Label37.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label37.configure(foreground="#c10000")
        Label37.configure(highlightbackground="#d9d9d9")
        Label37.configure(highlightcolor="black")
        Label37.configure(text='''MEAT''')

        Entry23 = tk.Entry(top)
        Entry23.place(relx=0.367, rely=0.652, height=34, relwidth=0.037)
        Entry23.configure(background="white")
        Entry23.configure(disabledforeground="#a3a3a3")
        Entry23.configure(font="TkFixedFont")
        Entry23.configure(foreground="#000000")
        Entry23.configure(insertbackground="black")
        Entry23.insert(0, "0")

        Entry24 = tk.Entry(top)
        Entry24.place(relx=0.367, rely=0.707, height=34, relwidth=0.037)
        Entry24.configure(background="white")
        Entry24.configure(disabledforeground="#a3a3a3")
        Entry24.configure(font="TkFixedFont")
        Entry24.configure(foreground="#000000")
        Entry24.configure(highlightbackground="#d9d9d9")
        Entry24.configure(highlightcolor="black")
        Entry24.configure(insertbackground="black")
        Entry24.configure(selectbackground="#c4c4c4")
        Entry24.configure(selectforeground="black")
        Entry24.insert(0, "0")

        Entry25 = tk.Entry(top)
        Entry25.place(relx=0.485, rely=0.652, height=34, relwidth=0.037)
        Entry25.configure(background="white")
        Entry25.configure(disabledforeground="#a3a3a3")
        Entry25.configure(font="TkFixedFont")
        Entry25.configure(foreground="#000000")
        Entry25.configure(highlightbackground="#d9d9d9")
        Entry25.configure(highlightcolor="black")
        Entry25.configure(insertbackground="black")
        Entry25.configure(selectbackground="#c4c4c4")
        Entry25.configure(selectforeground="black")
        Entry25.insert(0, "0")

        Entry26 = tk.Entry(top)
        Entry26.place(relx=0.485, rely=0.707, height=34, relwidth=0.037)
        Entry26.configure(background="white")
        Entry26.configure(disabledforeground="#a3a3a3")
        Entry26.configure(font="TkFixedFont")
        Entry26.configure(foreground="#000000")
        Entry26.configure(highlightbackground="#d9d9d9")
        Entry26.configure(highlightcolor="black")
        Entry26.configure(insertbackground="black")
        Entry26.configure(selectbackground="#c4c4c4")
        Entry26.configure(selectforeground="black")
        Entry26.insert(0, "0")

        Entry27 = tk.Entry(top)
        Entry27.place(relx=0.603, rely=0.652, height=34, relwidth=0.037)
        Entry27.configure(background="white")
        Entry27.configure(disabledforeground="#a3a3a3")
        Entry27.configure(font="TkFixedFont")
        Entry27.configure(foreground="#000000")
        Entry27.configure(highlightbackground="#d9d9d9")
        Entry27.configure(highlightcolor="black")
        Entry27.configure(insertbackground="black")
        Entry27.configure(selectbackground="#c4c4c4")
        Entry27.configure(selectforeground="black")
        Entry27.insert(0, "0")

        Entry28 = tk.Entry(top)
        Entry28.place(relx=0.603, rely=0.707, height=34, relwidth=0.037)
        Entry28.configure(background="white")
        Entry28.configure(disabledforeground="#a3a3a3")
        Entry28.configure(font="TkFixedFont")
        Entry28.configure(foreground="#000000")
        Entry28.configure(highlightbackground="#d9d9d9")
        Entry28.configure(highlightcolor="black")
        Entry28.configure(insertbackground="black")
        Entry28.configure(selectbackground="#c4c4c4")
        Entry28.configure(selectforeground="black")
        Entry28.insert(0, "0")

        Label38 = tk.Label(top)
        Label38.place(relx=0.679, rely=0.541, height=38, width=337)
        Label38.configure(activebackground="#f9f9f9")
        Label38.configure(activeforeground="black")
        Label38.configure(background="#ffffff")
        Label38.configure(disabledforeground="#a3a3a3")
        Label38.configure(
            font="-family {Copperplate Gothic Bold} -size 18 -weight bold -slant roman -underline 0 -overstrike 0")
        Label38.configure(foreground="#b90746")
        Label38.configure(highlightbackground="#d9d9d9")
        Label38.configure(highlightcolor="black")
        Label38.configure(text='''EXTRAS''')

        Label39 = tk.Label(top)
        Label39.place(relx=0.672, rely=0.597, height=36, width=258)
        Label39.configure(activebackground="#f9f9f9")
        Label39.configure(activeforeground="black")
        Label39.configure(background="#ffffff")
        Label39.configure(disabledforeground="#a3a3a3")
        Label39.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label39.configure(foreground="#008000")
        Label39.configure(highlightbackground="#d9d9d9")
        Label39.configure(highlightcolor="black")
        Label39.configure(text='''MEXICAN SANDWICH''')

        Label40 = tk.Label(top)
        Label40.place(relx=0.672, rely=0.641, height=36, width=239)
        Label40.configure(activebackground="#f9f9f9")
        Label40.configure(activeforeground="black")
        Label40.configure(background="#ffffff")
        Label40.configure(disabledforeground="#a3a3a3")
        Label40.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label40.configure(foreground="#008000")
        Label40.configure(highlightbackground="#d9d9d9")
        Label40.configure(highlightcolor="black")
        Label40.configure(text='''CHICKEN LASAGNA''')

        Label41 = tk.Label(top)
        Label41.place(relx=0.651, rely=0.685, height=36, width=250)
        Label41.configure(activebackground="#f9f9f9")
        Label41.configure(activeforeground="black")
        Label41.configure(background="#ffffff")
        Label41.configure(disabledforeground="#a3a3a3")
        Label41.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label41.configure(foreground="#008000")
        Label41.configure(highlightbackground="#d9d9d9")
        Label41.configure(highlightcolor="black")
        Label41.configure(text='''CHEESY FRIES''')

        Label42 = tk.Label(top)
        Label42.place(relx=0.658, rely=0.729, height=36, width=250)
        Label42.configure(activebackground="#f9f9f9")
        Label42.configure(activeforeground="black")
        Label42.configure(background="#ffffff")
        Label42.configure(disabledforeground="#a3a3a3")
        Label42.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label42.configure(foreground="#008000")
        Label42.configure(highlightbackground="#d9d9d9")
        Label42.configure(highlightcolor="black")
        Label42.configure(text='''CHICKEN PASTA''')

        Entry29 = tk.Entry(top)
        Entry29.place(relx=0.887, rely=0.608, height=24, relwidth=0.044)
        Entry29.configure(background="white")
        Entry29.configure(disabledforeground="#a3a3a3")
        Entry29.configure(font="TkFixedFont")
        Entry29.configure(foreground="#000000")
        Entry29.configure(highlightbackground="#d9d9d9")
        Entry29.configure(highlightcolor="black")
        Entry29.configure(insertbackground="black")
        Entry29.configure(selectbackground="#c4c4c4")
        Entry29.configure(selectforeground="black")
        Entry29.insert(0, "0")

        Entry30 = tk.Entry(top)
        Entry30.place(relx=0.887, rely=0.652, height=24, relwidth=0.044)
        Entry30.configure(background="white")
        Entry30.configure(disabledforeground="#a3a3a3")
        Entry30.configure(font="TkFixedFont")
        Entry30.configure(foreground="#000000")
        Entry30.configure(highlightbackground="#d9d9d9")
        Entry30.configure(highlightcolor="black")
        Entry30.configure(insertbackground="black")
        Entry30.configure(selectbackground="#c4c4c4")
        Entry30.configure(selectforeground="black")
        Entry30.insert(0, "0")

        Entry31 = tk.Entry(top)
        Entry31.place(relx=0.887, rely=0.696, height=24, relwidth=0.044)
        Entry31.configure(background="white")
        Entry31.configure(disabledforeground="#a3a3a3")
        Entry31.configure(font="TkFixedFont")
        Entry31.configure(foreground="#000000")
        Entry31.configure(highlightbackground="#d9d9d9")
        Entry31.configure(highlightcolor="black")
        Entry31.configure(insertbackground="black")
        Entry31.configure(selectbackground="#c4c4c4")
        Entry31.configure(selectforeground="black")
        Entry31.insert(0, "0")

        Entry32 = tk.Entry(top)
        Entry32.place(relx=0.887, rely=0.74, height=24, relwidth=0.044)
        Entry32.configure(background="white")
        Entry32.configure(disabledforeground="#a3a3a3")
        Entry32.configure(font="TkFixedFont")
        Entry32.configure(foreground="#000000")
        Entry32.configure(highlightbackground="#d9d9d9")
        Entry32.configure(highlightcolor="black")
        Entry32.configure(insertbackground="black")
        Entry32.configure(selectbackground="#c4c4c4")
        Entry32.configure(selectforeground="black")
        Entry32.insert(0, "0")

        TotalButton1 = tk.Button(top,command=lambda:[totalobj.calculation(), totalgui.totalwindow() ])
        TotalButton1.place(relx=0.811, rely=0.818, height=53, width=176)
        TotalButton1.configure(activebackground="#ececec")
        TotalButton1.configure(activeforeground="#000000")
        TotalButton1.configure(background="#b90746")
        TotalButton1.configure(disabledforeground="#a3a3a3")
        TotalButton1.configure(font=14)
        TotalButton1.configure(font="-family {Cooper Black} -size 11 -weight normal -slant roman -underline 0 -overstrike 0")
        TotalButton1.configure(foreground="#ffffff")
        TotalButton1.configure(highlightbackground="#d9d9d9")
        TotalButton1.configure(highlightcolor="black")
        TotalButton1.configure(pady="0")
        TotalButton1.configure(text='''TOTAL''')

        Button1_22 = tk.Button(top,command = resetobj.Reset)
        Button1_22.place(relx=0.811, rely=0.917, height=53, width=176)
        Button1_22.configure(activebackground="#ececec")
        Button1_22.configure(activeforeground="#000000")
        Button1_22.configure(background="#b90746")
        Button1_22.configure(disabledforeground="#a3a3a3")
        Button1_22.configure(font="-family {Cooper Black} -size 11 -weight normal -slant roman -underline 0 -overstrike 0")
        Button1_22.configure(foreground="#ffffff")
        Button1_22.configure(highlightbackground="#d9d9d9")
        Button1_22.configure(highlightcolor="black")
        Button1_22.configure(pady="0")
        Button1_22.configure(text='''RESET''')

        Label43 = tk.Label(top)
        Label43.place(relx=0.333, rely=0.785, height=38, width=337)
        Label43.configure(activebackground="#f9f9f9")
        Label43.configure(activeforeground="black")
        Label43.configure(background="#ffffff")
        Label43.configure(disabledforeground="#a3a3a3")
        Label43.configure(
            font="-family {Copperplate Gothic Bold} -size 18 -weight bold -slant roman -underline 0 -overstrike 0")
        Label43.configure(foreground="#b90746")
        Label43.configure(highlightbackground="#d9d9d9")
        Label43.configure(highlightcolor="black")
        Label43.configure(text='''KIDS SPECIAL''')

        Label44 = tk.Label(top)
        Label44.place(relx=0.353, rely=0.84, height=46, width=129)
        Label44.configure(activebackground="#f9f9f9")
        Label44.configure(activeforeground="black")
        Label44.configure(background="#ffffff")
        Label44.configure(disabledforeground="#a3a3a3")
        Label44.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label44.configure(foreground="#008000")
        Label44.configure(highlightbackground="#d9d9d9")
        Label44.configure(highlightcolor="black")
        Label44.configure(text='''DEAL 1''')

        Label45 = tk.Label(top)
        Label45.place(relx=0.34, rely=0.906, height=37, width=161)
        Label45.configure(activebackground="#f9f9f9")
        Label45.configure(activeforeground="black")
        Label45.configure(background="#ffffff")
        Label45.configure(cursor="fleur")
        Label45.configure(disabledforeground="#a3a3a3")
        Label45.configure(
            font="-family {Copperplate Gothic Light} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        Label45.configure(foreground="#008000")
        Label45.configure(highlightbackground="#d9d9d9")
        Label45.configure(highlightcolor="black")
        Label45.configure(text='''DEAL 2''')

        Entry33 = tk.Entry(top)
        Entry33.place(relx=0.478, rely=0.851, height=24, relwidth=0.051)
        Entry33.configure(background="white")
        Entry33.configure(disabledforeground="#a3a3a3")
        Entry33.configure(font="TkFixedFont")
        Entry33.configure(foreground="#000000")
        Entry33.configure(highlightbackground="#d9d9d9")
        Entry33.configure(highlightcolor="black")
        Entry33.configure(insertbackground="black")
        Entry33.configure(selectbackground="#c4c4c4")
        Entry33.configure(selectforeground="black")
        Entry33.insert(0, "0")

        Entry34 = tk.Entry(top)
        Entry34.place(relx=0.478, rely=0.917, height=24, relwidth=0.051)
        Entry34.configure(background="white")
        Entry34.configure(disabledforeground="#a3a3a3")
        Entry34.configure(font="TkFixedFont")
        Entry34.configure(foreground="#000000")
        Entry34.configure(highlightbackground="#d9d9d9")
        Entry34.configure(highlightcolor="black")
        Entry34.configure(insertbackground="black")
        Entry34.configure(selectbackground="#c4c4c4")
        Entry34.configure(selectforeground="black")
        Entry34.insert(0, "0")
        top.mainloop()


class TotalwindowGUI:
    def totalwindow(self):

        top = Tk()
        top.geometry("600x437+630+337")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("CALIFORNIA PIZZA BILL")
        top.configure(background="#ffffff")

        recpno = tk.Entry(top)
        recpno.place(relx=0.333, rely=0.183, relheight=0.094, relwidth=0.59)
        recpno.configure(background="white")
        recpno.configure(font="TkTextFont")
        recpno.configure(font=10)
        recpno.configure(foreground="black")
        recpno.configure(highlightbackground="#d9d9d9")
        recpno.configure(highlightcolor="black")
        recpno.configure(insertbackground="black")
        recpno.configure(selectbackground="#c4c4c4")
        recpno.configure(selectforeground="black")
        number = random.randint(1000, 9999)
        recpno.insert(0,number)


        Label1 = tk.Label(top)
        Label1.place(relx=0.017, rely=0.183, height=39, width=182)
        Label1.configure(background="#ffffff")
        Label1.configure(disabledforeground="#a3a3a3")
        Label1.configure(font=11)
        Label1.configure(foreground="#b90746")
        Label1.configure(text='''RECEIPT NUMBER''')

        Label2 = tk.Label(top)
        Label2.place(relx=0.117, rely=0.343, height=39, width=82)
        Label2.configure(background="#ffffff")
        Label2.configure(disabledforeground="#a3a3a3")
        Label2.configure(font=9)
        Label2.configure(foreground="#b90746")
        Label2.configure(text='''DATE''')

        Label3 = tk.Label(top)
        Label3.place(relx=0.133, rely=0.503, height=39, width=62)
        Label3.configure(background="#ffffff")
        Label3.configure(disabledforeground="#a3a3a3")
        Label3.configure(font=9)
        Label3.configure(foreground="#b90746")
        Label3.configure(text='''TIME''')

        Label4 = tk.Label(top)
        Label4.place(relx=0.017, rely=0.664, height=39, width=182)
        Label4.configure(background="#ffffff")
        Label4.configure(disabledforeground="#a3a3a3")
        Label4.configure(font=9)
        Label4.configure(foreground="#b90746")
        Label4.configure(text='''TOTAL AMOUNT''')

        Label5 = tk.Label(top)
        Label5.place(relx=0.383, rely=0.046, height=26, width=152)
        Label5.configure(background="#ffffff")
        Label5.configure(disabledforeground="#a3a3a3")
        Label5.configure(font=10)
        Label5.configure(foreground="#008000")
        Label5.configure(text='''RECEIPT''')

        Date = tk.Entry(top)
        Date.place(relx=0.333, rely=0.343, relheight=0.101, relwidth=0.59)
        Date.configure(background="white")
        Date.configure(font="TkTextFont")
        Date.configure(foreground="black")
        Date.configure(highlightbackground="#d9d9d9")
        Date.configure(highlightcolor="black")
        Date.configure(font=10)
        Date.configure(insertbackground="black")
        Date.configure(selectbackground="#c4c4c4")
        Date.configure(selectforeground="black")
        today = date.today()
        Date.insert(0, today.strftime("%B %d, %Y"))

        Time = tk.Entry(top)
        Time.place(relx=0.333, rely=0.503, relheight=0.101, relwidth=0.59)
        Time.configure(background="white")
        Time.configure(font="TkTextFont")
        Time.configure(foreground="black")
        Time.configure(font=10)
        Time.configure(highlightbackground="#d9d9d9")
        Time.configure(highlightcolor="black")
        Time.configure(insertbackground="black")
        Time.configure(selectbackground="#c4c4c4")
        Time.configure(selectforeground="black")
        today1 = datetime.now()
        Time.insert(0, today1.strftime("%H:%M:%S"))

        Totalamount = tk.Entry(top)
        Totalamount.place(relx=0.333, rely=0.664, relheight=0.101, relwidth=0.59)
        Totalamount.configure(background="white")
        Totalamount.configure(font="TkTextFont")
        Totalamount.configure(foreground="black")
        Totalamount.configure(font=10)
        Totalamount.configure(highlightbackground="#d9d9d9")
        Totalamount.configure(highlightcolor="black")
        Totalamount.configure(selectbackground="#c4c4c4")
        Totalamount.configure(selectforeground="black")
        Totalamount.insert(END,"Rs. ")
        Totalamount.insert(END,Total)

        Label5 = tk.Label(top)
        Label5.place(relx=0.393, rely=0.797, height=26, width=222)
        Label5.configure(background="#ffffff")
        Label5.configure(disabledforeground="#a3a3a3")
        Label5.configure(font=10)
        Label5.configure(foreground="#008000")
        Label5.configure(text='''THANKS FOR BUYING''')
        top.mainloop()




def login():
    ID = Entry1.get()
    Password = Entry2.get()
    global User
    for i in range(3000):
        infile = open("UserID.txt", 'r+')
        content = infile.read()
        listofidpw = content.split()
        if ID not in listofidpw:
            tkinter.messagebox.showinfo("Error", "Access denied, Invalid Username")
            break
        else:
            pwindex = listofidpw.index(ID) + 1

        if listofidpw[pwindex] == Password:
            User = ID
            tkinter.messagebox.showinfo("Login", "Logged In Successfully")
            top.destroy()
            obj.secondwindow()

            break
        else:
            tkinter.messagebox.showinfo("Error", "Access denied, Invalid Password")
            break

def register():
    UserName = Entry1.get()
    Password = Entry2.get()

    infile = open("UserID.txt", 'r+')
    content = infile.read()
    listofidpw = content.split()
    if UserName in listofidpw:
        tkinter.messagebox.showinfo("Error", "User Already Exist")
    elif (UserName == "") or (Password == ""):
        tkinter.messagebox.showinfo("Error", "InValid Data Entered")
    else:
        infile = open('UserID.txt', 'r+')
        content = infile.read()
        infile.write(" {0} {1}".format(UserName, Password))
        tkinter.messagebox.showinfo("Success", "Customer Registered Successfully")
        infile.close()

obj = GUI()
totalobj = total()
resetobj = reset()
totalgui = TotalwindowGUI()
obj.maingui()
